### ISSUE TITLE
Stuck on boot screen

### ISSUE THREAD

**Issue by fredvey** [bangbaew/Gigabyte-B460M-DS3H-Hackintosh#2]

**Comment by bangbaew** [comment]
For me, I was able to boot on default BIOS settings, but try following the OpenCore guide here.

# Disable
Fast Boot
Secure Boot
VT-d (can be enabled if you set DisableIoMapper to YES)
CSM
Thunderbolt(For initial install, as Thunderbolt can cause issues if not setup correctly)
Intel SGX
Intel Platform Trust
CFG Lock (MSR 0xE2 write protection)(This must be off, if you can't find the option then enable both AppleCpuPmCfgLock and AppleXcpmCfgLock under Kernel -> Quirks. Your hack will not boot with CFG-Lock enabled)

# Enable
VT-x
Above 4G decoding
Hyper-Threading
Execute Disable Bit
EHCI/XHCI Hand-off
OS type: Windows 8.1/10 UEFI Mode
DVMT Pre-Allocated(iGPU Memory): 64MB
